import type { ArchGraph } from '@sequence/schema';

/**
 * Deterministic SQL DDL generation from an architecture spec.
 *
 * This closes the documented v5 "no DDL mandated" gap at the generation layer:
 * the vision's schema case ("select a db region → right-click → generate a
 * schema table"). The honest artifact is a table SKELETON, not invented columns
 * — the spec carries which services access which tables (db edges + detail.table
 * on postgres datastores), but NOT their columns. So each distinct table gets:
 *
 *   -- a title comment naming the accessing service(s)
 *   CREATE TABLE IF NOT EXISTS <table> (
 *     id serial primary key
 *     -- columns beyond the key are intentionally left to the implementer
 *   );
 *
 * Pure and deterministic by construction: tables are the distinct
 * `detail.table` values on db edges (db_access/db_read/db_write) whose target is
 * a `postgres` datastore, emitted in sorted order with sorted accessor lists —
 * so the same spec always renders byte-identical SQL (snapshot-stable). A spec
 * with no such edges renders a comment-only file. No fs, no randomness, no
 * timestamps; runs unchanged in the browser and on the server.
 */

const DB_EDGE_KINDS = new Set(['db_access', 'db_read', 'db_write']);

/** True when `graph` has at least one db edge targeting a postgres datastore. */
export function hasDbTables(graph: ArchGraph): boolean {
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  return graph.edges.some((e) => {
    if (!DB_EDGE_KINDS.has(e.kind)) return false;
    const dst = byId.get(e.dstId);
    return !!dst && dst.kind === 'datastore' && dst.meta?.tech === 'postgres' && !!e.detail?.table;
  });
}

export function renderDDL(graph: ArchGraph): string {
  const byId = new Map(graph.nodes.map((n) => [n.id, n]));
  // table name -> set of accessing service labels (both sides deterministic).
  const tables = new Map<string, Set<string>>();
  for (const e of graph.edges) {
    if (!DB_EDGE_KINDS.has(e.kind)) continue;
    const dst = byId.get(e.dstId);
    if (!dst || dst.kind !== 'datastore' || dst.meta?.tech !== 'postgres') continue;
    const table = e.detail?.table;
    if (!table) continue;
    const accessor = byId.get(e.srcId)?.label ?? e.srcId;
    let set = tables.get(table);
    if (!set) tables.set(table, (set = new Set<string>()));
    set.add(accessor);
  }

  const L: string[] = [];
  L.push('-- Schema DDL generated by sequence from the architecture spec.');
  L.push('-- The spec models which services access which tables, not their columns,');
  L.push('-- so each table carries only its primary key; columns beyond it are left');
  L.push('-- to the implementer (add them as the accessing service requires).');
  L.push('');
  if (tables.size === 0) {
    L.push('-- No tables: this spec has no db edges targeting a postgres datastore.');
    return L.join('\n') + '\n';
  }
  const names = [...tables.keys()].sort();
  names.forEach((table, i) => {
    const accessors = [...tables.get(table)!].sort();
    L.push(`-- table "${table}" — accessed by: ${accessors.join(', ')}`);
    L.push(`CREATE TABLE IF NOT EXISTS ${table} (`);
    L.push('  id serial primary key');
    L.push('  -- columns beyond the key are intentionally left to the implementer');
    L.push(');');
    if (i < names.length - 1) L.push('');
  });
  return L.join('\n') + '\n';
}
